[package]
name = "taskbar-api"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "D-Bus contracts and client proxies for taskbar"
rust-version.workspace = true

[dependencies]
taskbar-core.workspace = true
serde.workspace = true
zbus.workspace = true
zvariant.workspace = true
